### ISSUE TITLE
[0.5] Media - Map

### ISSUE THREAD

**Issue by Yago** [epfl-si/elements#110]
Add a variant to Component/Map 😉 

<img width="647" alt="capture d ecran 2018-05-18 a 09 36 34" src="https://user-images.githubusercontent.com/2025924/40222176-fc475cba-5a7e-11e8-82b6-09646a877c81.png">

**Comment by zufrieden** [comment]
There is a shortcode to display map from https://plan.epfl.ch/
More on that later

**Comment by knuch** [comment]
URL for the iframe url of the map : https://plan.epfl.ch/iframe/?dim_floor=0&lang=fr&dim_lang=fr&tree_group_layers_developpement_durable=&baselayer_ref=grp_backgrounds&map_x=533044&map_y=152396&map_zoom=8&tree_groups=centres_nevralgiques%2Cacces%2Cmobilite_reduite%2Censeignement%2Ccommerces_et_services%2Cvehicules%2Cinfrastructure_plan_grp&tree_group_layers_centres_nevralgiques=&tree_group_layers_acces=&tree_group_layers_mobilite_reduite=&tree_group_layers_enseignement=&tree_group_layers_commerces_et_services=imprimantes&tree_group_layers_vehicules=&tree_group_layers_infrastructure_plan_grp=
