### ISSUE TITLE
[8h] Article page

### ISSUE THREAD

**Issue by guillaumeberry** [epfl-si/elements#126]
- [ ] **Header** should be the **light version** (see attached capture, behavior NOT YET validated, we simply put a light version of the header).
- [ ] **Footer** should be the **light version**.
- [ ] Page to be **renamed “News detail page”** as it's a template specific to the actu app
- [ ] **The cover image should be full-width.** That's an exception we are making as all highlight news promoted by Mediacom have well crafted / quality media (photo & video). Not all services and news media share this level of quality.
- [ ] Add author & source at the end of the content
- [ ] Review sidebar
- [ ] Create a variation of this page with a teaser + video player instead of the full-width cover.

—› 🎨 Mockups of this page have been updated based on client's feedback:
https://invis.io/8GJW7I94JAZ

---

![actu-header](https://user-images.githubusercontent.com/33514073/40784103-e38c9e40-64e4-11e8-99a2-1f2a8e244a0f.png)

**Comment by zufrieden** [comment]
Not a COPIL priority focus on wordpress
