### ISSUE TITLE
Search input a11y

### ISSUE THREAD

**Issue by tonifisler** [epfl-si/elements#134]
As a user, I would want to click on the icon button of the Search input (`/#/atoms/search`) but I can't. 🤔 

![search-input](https://user-images.githubusercontent.com/1708450/41222114-61d5b942-6d66-11e8-82bc-91e58f462ec4.gif)

**Comment by xentenza** [comment]
Plus d'actualité
https://epfl-si.github.io/elements/#/molecules/search
