### ISSUE TITLE
Accueil faculté

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#160]
[Maquettes - sans la navigation aside](https://invis.io/9DMZV08HJ6Z#/286230780_School_Generic_desktop-3)
## Examples 
enac.epfl.ch
sti.epfl.ch
sb.epfl.ch
ic.epfl.ch
sv.epfl.ch
cdm.epfl.ch
cdh.epfl.ch

## Goal
- Explain the subject of the faculty (environnement, sciences, informatiques, etc.)
- Show the whole offer (what's going on in this faculty)

### Context
Component : [Hero](https://epfl-idevelop.github.io/elements/#/organisms/hero)
Give the context
### News
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news) (basic teaser)
The last 3 news shows what is happening in this faculty
### Highlighted projects
Component : [Research project](https://epfl-idevelop.github.io/elements/#/content-types/research-project)
Highlighting a few projects illustrates concretely what the faculty is doing
#### Education
Component : [Section](https://epfl-idevelop.github.io/elements/#/content-types/section) (Section) 
What are the sections that compose the faculty
#### Research
Component : [Insitute](https://epfl-idevelop.github.io/elements/#/content-types/institutes) (Institute) 
What are the institutes that are part of the faculty
#### Innovation
Component : [Research Project](https://epfl-idevelop.github.io/elements/#/content-types/research-project
Highlighting a few projects illustrates concretely what the faculty is doing
### Events
Component : [Event](https://epfl-idevelop.github.io/elements/#/content-types//event) (Slider wrapper)
There are many activities within EPFL, this section highlights those who go on in the faculty

**Comment by nsz** [comment]
Idéalement : avoir 2 pages de facultés (une avec les instituts et l'autre sans)
**Avec les instituts : à valider par un adjoint de facultés (Corinne/Matteo)
Sans les instituts : Corinne fait une proposition**

**Comment by cfeuz** [comment]
j'aime bien le design. @Magaly, voir comment on décline pour facultés avec/sans instituts. Si possible, présenter à Marilyne Andersen. 

@nsz  il manque de mon point de vu un élément contact avec Adresse, tél. J'aurai pour systématique de mettre pour chaque faculté, dans le même esprit que ce que demandé par Antoinette pour recherche

**Comment by nsz** [comment]
@frizzymagma

**Comment by frizzymagma** [comment]
@nsz Les composants : 
- [ ] Header
- [ ] Breadcrumb
- [ ] Nav aside
- [ ] Hero 
- [ ] News
- [ ] Highlighted teaser (temps fort de la faculté)
- [ ] Education : 3 blocks basic page teaser / section component
- [ ] Research : 3 blocks basic page teaser / institute component
- [ ] Innovation : 3 blocks basic page teaser / projects component
- [ ] Events
- [ ] Twitter feed + Basic page teaser + Links block
- [ ] Footer
