### ISSUE TITLE
[2h] error pages (like 404, 500)

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#163]
## Goal
- Inform visitors that there is nothing at this URL
- Offer them other interesting and relevant contents

### Context
Component : [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Explain that there is an error, it's not user fault.
404 -> nothing at this URL
500 -> There is an error

### Redirection
Component : [Basic page](https://epfl-idevelop.github.io/elements/#/content-types/basic-page)
Redirect visitors to the relevant pages:
- Homepage
- Faculties
## Open questions 
- This page can be more "fun", can we add something (picture, game, etc.) ?

**Comment by nsz** [comment]
Il est important de mettre en avant la homepage
La page des news n'est pas nécessaire.

**Comment by pierre-georges** [comment]
Proposition pour la page 404.
https://invis.io/9DMZV08HJ6Z#/319504359_error_404
Pour animer un peu, j'imaginais les étoiles qui défilent très légèrement et la fusée qui "flotte".

**Comment by frizzymagma** [comment]
Hello @zufrieden, comme discuté, ce design bien que cool n'est pas adapté : il ne fait pas assez "sérieux", privilégie un domaine de recherche spécifique (et donc risque de froisser une bonne partie des chercheurs) et on souhaiterait avoir quelque chose de plus "classique".

**Comment by frizzymagma** [comment]
@zufrieden Je n'ai pas compris le "ajouter un champ de recherche" ?

**Comment by xentenza** [comment]
Nouveau cahier des charges pour les pages d'erreur
https://epfl-webvolution.atlassian.net/browse/WEBEVOL-79
