### ISSUE TITLE
Tous les labos

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#164]
## Goal
- List laboratories

### Context
Component : [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Title, explication about what is a laboratory in the EPFL
### Laboratories list
*Component : [Laboratory](https://epfl-idevelop.github.io/elements/#/content-types/laboratory)* 
Because there are a large number of laboratories, it is more judicious to display them as a list.
### Filters
Component : [Filters](https://epfl-idevelop.github.io/elements/#/molecules/filters)
It is interesting to be able to filter laboratories by faculty (sections?) and institutes.
## Open questions
- Is a [pagination](https://epfl-idevelop.github.io/elements/#/molecules/pagination) necessary ?
- A component **is missing** to display the labs as a list : just with the title (accronyme) and the teacher.

**Comment by nsz** [comment]
Liste de labo : nom du labo en toutes lettres (l'acronyme entre parenthèse) et le nom du prof
Filtre : faculté, section et instituts (par thématique/tag ?)
à coder !

**Comment by nsz** [comment]
@Yago @pierre-georges @guillaumeberry il me manque un composant **teaser labo sous forme de liste**.
Il contient le nom du labo en toutes lettres (l'acronyme entre parenthèse) et le nom du prof.

**Comment by pierre-georges** [comment]
@nsz @guillaumeberry
J'ai fais deux versions.
https://invis.io/9DMZV08HJ6Z#/279353737_Teaser-Mission
P1: Liste de cartes version "small"
P2: Liste en lignes
Qu'est-ce qui est le plus approprié ?

**Comment by nsz** [comment]
merci @pierre-georges 
Franchement je trouve que la liste en lignes fonctionne très bien, vu la grande quantité de labos !

Tu en penses quoi @guillaumeberry ?

**Comment by guillaumeberry** [comment]
@nsz @pierre-georges yup, liste en ligne is a go!
attention à pas faire une liste avec -tous- les labos, load more / pagination / ABCD
on a des solutions pour pas que ça devienne un annuaire interminable.

**Comment by pierre-georges** [comment]
Yes, composants existants: https://projects.invisionapp.com/share/9DMZV08HJ6Z#/screens/294637516_Pagination

**Comment by nsz** [comment]
En attente du composant labo pour la liste.
