### ISSUE TITLE
[0.5] À propos --> page de "niveau 1" - Ajouter quote

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#170]
[Wireframe](https://invis.io/KJN0UK34D2C#/261724060_A-_Propos)
## Goal
- Explain to someone who does not know what EPFL is
- Redirect visitors for everything that concerns the administrative side of EPFL (jobs, history, donations, alumni, etc.)
### Context
Component : 
- [Hero](https://epfl-idevelop.github.io/elements/#/organisms/hero)
Image and title
- [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Explication about the EPFL
### News
Component : 
- [News](https://epfl-idevelop.github.io/elements/#/content-types/news) 
Latest news about the EPFL and link to all the news
### Video + Useful links
Component : 
- [Video] (https://epfl-idevelop.github.io/elements/#/atoms/video) (Video)
- [Link] (https://epfl-idevelop.github.io/elements/#/molecules/links-group) (Link teaser)
Another way to show what is the EPFL about
### Basic page (History, Organisation, Press, donation, actions for external people)
Component : [Basic page](https://epfl-idevelop.github.io/elements/#/content-types/basic-page) (Basic teaser)
### Jobs
Show the offer / explain how to work at EPFL
### Alumnis
Link to the association (teaser basic page ?) / Testimonial / Famous Alumni (teaser basic page ?)
## Open questions
- Is there a component for jobs ?
- Is there a component for Alumni/Testimonial ?

**Comment by nsz** [comment]
**- à faire valider par Adrian**
- les emplois (6 août)
- il manque : composant : "politique en matière de développement durable" et un accès les événements (gestion des événements)
<img width="1045" alt="capture d ecran 2018-07-26 a 10 33 04" src="https://user-images.githubusercontent.com/1941982/43251101-50ebb600-90bf-11e8-9d8e-dbb8c96da24b.png">
- affiner la partie "administrative"

**Comment by cfeuz** [comment]
J'ai retransmis les deux questions à Magaly, qui rentre lundi (pour emploi, on aura la réponse rapidement). Pour politique en matière de développement durable, à voir avec Adrìan Magaly le wording à utilisé. Si bloquant, on laisse un bloc gris pour l'heure

**Comment by nsz** [comment]
@frizzymagma

**Comment by frizzymagma** [comment]
Hello @nsz voici notre retour pour le template A propos : 

- [ ] Header
- [ ] Breadcrumb
- [ ] Image (hero) ou vidéo
- [ ] Introduction
- [ ] Bloc de liens + basic page teaser (1 bloc) + Bloc links teaser 
- [ ] News
- [ ] Basic page teaser (1 bloc) + Bloc links teaser + Basic page teaser (1 bloc)
- [ ] Événements
- [ ] Basic page teaser (1 bloc) + Basic page teaser (1 bloc)
- [ ] Quote + Basic page teaser (1 bloc)
- [ ] Footer

**Comment by nsz** [comment]
We just need #159 to be ready

@zufrieden ready to review

**Comment by zufrieden** [comment]
- [ ] Ajouter la quote magique
