### ISSUE TITLE
Pretty printé le HTML du styleguide

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-si/elements#173]
Dans le [Styleguide](https://epfl-idevelop.github.io/elements/), de nombreux composants ont leur HTML qui n'est pas pretty printé.

Exemple : https://epfl-idevelop.github.io/elements/#/components/event

**Comment by zufrieden** [comment]
@GregLeBarbar merci pour le feedback.
Tu penses à l'indentation ?

**Comment by knuch** [comment]
Après inspection, le HTML des fichiers Twig du styleguide sont majoritairement indentés correctement. Il s'agit ici d'une mauvais interprétation des carriage returns par *toolbox-reader* lorsqu'on utilise des balises twig du genre {% block date %}` si je ne m'abuse. 
à fixer dans une release prochaine

**Comment by frizzymagma** [comment]
@GregLeBarbar @knuch  Est-ce que c'est corrigé ? Merci.

**Comment by zufrieden** [comment]
Comme expliqué par @knuch cela dépend du toolbox-reader, j'ai ouvert une issue ici https://github.com/frontend/toolbox-reader/issues/43 pour en discuter.
