### ISSUE TITLE
Recherche --> page de "niveau 1" - Ajouter quote

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#174]
[Wireframe](https://invis.io/KJN0UK34D2C#/261736033_Recherche)
## Goal
- Inform about what is done as research at EPFL
- Redirect visitors for everything that concerns the research side of EPFL (projects, laboratories, etc.)
### Context
Component : 
- [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Title, explanation about the EPFL research
- [Publications](https://epfl-idevelop.github.io/elements/#/content-types/publication)
Latest publications
### News
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news) 
Latest news about the EPFL and link to all the news
### Event
Component : [Event](https://epfl-idevelop.github.io/elements/#/content-types/event) (Slider wrapper)
Next events
### Research
Components : 
- [Research field](https://epfl-idevelop.github.io/elements/#/content-types/research-field)
Some research fields and the link to all of them
- [Research project](https://epfl-idevelop.github.io/elements/#/content-types/research-project) 
Current projet
### [Footer](https://epfl-idevelop.github.io/elements/#/organisms/footer)

**Comment by nsz** [comment]
Contenu demandé par Corinne et Antoinette : 

![capture d ecran 2018-08-02 a 09 14 20](https://user-images.githubusercontent.com/1941982/43568335-9cbb43a0-9634-11e8-8101-f7da7adc4b62.png)

[Research_NB_2.pdf](https://github.com/epfl-idevelop/elements/files/2252489/Research_NB_2.pdf)
[Uploading Research_NB.pdf…]()

**Comment by cfeuz** [comment]
Hello, oui c'est possible de passer par github. mon identifiant doit s'afficher, non?

**Comment by nsz** [comment]
@cfeuz oui c'est tout bon, merci :)

**Comment by nsz** [comment]
ready to review : https://github.com/epfl-idevelop/elements/pull/216/commits/c45e5d71a702e4f50245115afcff46533766ae45

**Comment by nsz** [comment]
@knuch @Yago 
il manque le composant https://github.com/epfl-idevelop/elements/issues/158

Et est-ce qu'on a un composant "citation" @guillaumeberry @pierre-georges ?
<img width="954" alt="capture d ecran 2018-08-02 a 15 49 18" src="https://user-images.githubusercontent.com/1941982/43587940-a6e03c5a-966b-11e8-9da6-ef6bcf70493c.png">

**Comment by guillaumeberry** [comment]
@nsz on a le style “quote” par ici : [https://epfl-idevelop.github.io/elements/#/doc/typography.html](https://epfl-idevelop.github.io/elements/#/doc/typography.html)

On a aussi une version de quote avec portrait, mais qui était dédié au alumnis… Jusqu'à maintenant ^_^

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, à reviewé : https://epfl-idevelop.github.io/elements/#/pages/research

**Comment by zufrieden** [comment]
Depend on #238
