### ISSUE TITLE
Datepicker event

### ISSUE THREAD

**Issue by Yago** [epfl-si/elements#19]
Base on the datepicker done on #6 it's the [custom event datepicker](https://invis.io/N4FDSKWX8ZB#/279353744_Form-Standard-Calendar-And-Filters).

![capture d ecran 2018-03-09 a 13 59 03](https://user-images.githubusercontent.com/2025924/37208666-771d5e94-23a2-11e8-9937-68f8b70e5543.png)

**Comment by knuch** [comment]
Top component coded . Behavior with event listed under is to be defined and coded in js when we have access to the content.

**Comment by Yago** [comment]
Regressions fixed with the huge refactoring sprint !

**Comment by Yago** [comment]
Still need some interaction from the datepicker with the `content-types/event/event-slider` @zufrieden or @guillaumeberry in the styleguide ?
