### ISSUE TITLE
News detail page

### ISSUE THREAD

**Issue by frizzymagma** [epfl-si/elements#233]
Il manque des informations sur le template "news detail" : date, auteur, source, taille de l'image, etc. 

La maquette présentée sur https://projects.invisionapp.com/share/ETEEFVHSQ#/screens/287942721 est plus complète. 

D'autre part, quelle présentation lorsqu'on insère une vidéo sur une actu ? 

Merci

**Comment by zufrieden** [comment]
List of pages : https://github.com/epfl-idevelop/elements/issues/152

See page : https://epfl-idevelop.github.io/elements/#/pages/news-detail

Maquette (Certains points encore à discuter avant de coder)
![screenshot 2018-08-15 10 36 31](https://user-images.githubusercontent.com/451236/44139350-1f0dfa4a-a077-11e8-9fc7-4532f9d0c429.png)

**Comment by pierre-georges** [comment]
Màj avec la vidéo.
https://invis.io/9DMZV08HJ6Z#/287942722_News-Details-After-A

**Comment by zufrieden** [comment]
Validé par @frizzymagma
