### ISSUE TITLE
labo list

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#239]
On a besoin d'un composant pour lister les labos : https://github.com/epfl-idevelop/elements/issues/164

Liste en ligne : https://invis.io/9DMZV08HJ6Z#/279353737_Teaser-Mission cc. @pierre-georges @guillaumeberry 

"attention à pas faire une liste avec -tous- les labos, load more / pagination / ABCD
on a des solutions pour pas que ça devienne un annuaire interminable."

**Comment by zufrieden** [comment]
## Sans image et sans teaser texte
![screenshot 2018-09-12 13 44 01](https://user-images.githubusercontent.com/451236/45422889-ec8d5a80-b691-11e8-808f-fa460fd6be94.png)

## Avec
![screenshot 2018-09-12 13 43 56](https://user-images.githubusercontent.com/451236/45422890-ed25f100-b691-11e8-858b-cdd8924575dc.png)

Labo list, using cards ;-) 
Merci de valider le design ci-dessus @frizzymagma

**Comment by zufrieden** [comment]
À discuter avec @lvenries pour voir les plans de la VPSI pour l'implémentation d'un shortcode webservice "Labos"

Standby.

**Comment by lvenries** [comment]
On a notre propre composant
