### ISSUE TITLE
Page accueil revue de presse

### ISSUE THREAD

**Issue by nsz** [epfl-si/elements#243]
[Exemple](https://rdp.epfl.ch/)

## Goal
List all the press review

### [Footer](https://epfl-idevelop.github.io/elements/#/organisms/footer)

**Comment by nsz** [comment]
@frizzymagma est-ce que le contenu est ok pour toi ?

**Comment by frizzymagma** [comment]
@nsz Y aurait-il besoin d'une pagination (cf. rdp.epfl.ch) ? Et il faudrait intégrer un bouton / champ pour s'abonner. 

Autrement, c'est ok. Merci

**Comment by zufrieden** [comment]
@frizzymagma se renseigne sur qui va s'occuper de l'implémentation de ce template dans un outil, et est-ce nécessaire de le documenter.
