### ISSUE TITLE
[4] Iconography

### ISSUE THREAD

**Issue by zufrieden** [epfl-si/elements#289]
Today list is https://static.epfl.ch/latest/doc/styleguide/icons.html#icons

## In the new version, we have  : 
- [x] accessibility.svg
- [x] arrow-left.svg
- [x] arrow-right.svg
- [x] browse.svg
- [x] chevron-last-left.svg
- [x] chevron-last-right.svg
- [x] chevron-left.svg
- [x] chevron-right.svg
- [x] close.svg
- [x] elements.svg
- [x] facebook.svg
- [x] googleplus.svg
- [x] home.svg
- [x] info.svg
- [x] instagram.svg
- [x] lock.svg
- [x] mail-plane.svg
- [x] search-bold.svg
- [x] search.svg
- [x] svg-icons.js
- [x] triangle.svg
- [x] twitter.svg
- [x] upload.svg
- [x] whatsapp.svg

**Comment by knuch** [comment]
To add:

- [ ] Add to calendar icon

**Comment by zufrieden** [comment]
On propose d'intégrer la librairie https://feathericons.com/

**Comment by zufrieden** [comment]
@frizzymagma valide d'ajouter toute la librairie feathericons dans Elements

**Comment by knuch** [comment]
todo:
- [ ] Implémenter feathericon

- [ ] lister les icones de remplacement des icones actuelles

- [ ] lister les nouvelles icones

- [ ] lister les icones manquantes et proposer des substituts

- [ ] créer les icones manquantes et non substituable
