### ISSUE TITLE
[2] Bouton - retour en haut de la page

### ISSUE THREAD

**Issue by zufrieden** [epfl-si/elements#290]

**Comment by pierre-georges** [comment]
J'ai repris la taille hauteur/largeur des boutons, hors grille sur le côté.
Fond gris avec bord blanc pour être visible partout (voir à cheval sur la section avec la vidéo en haut).
https://invis.io/9DMZV08HJ6Z#/287942722_News-Details-After-A

A voir au dev sur différentes pages si ça fonctionne bien.

**Comment by zufrieden** [comment]
Yes merci @pierre-georges 
@knuch commentaires bienvenus ;-)

**Comment by zufrieden** [comment]
![screenshot 2018-09-12 17 32 43](https://user-images.githubusercontent.com/451236/45435922-e313ea80-b6b1-11e8-819e-ed19a1cb362f.png)

- [ ] Apparait en bas à droite dès qu'on scrollé 1vh
