### ISSUE TITLE
Il manque le layout pour le bouton de connexion

### ISSUE THREAD

**Issue by obieler** [epfl-si/elements#336]
**Voici une idée de proposition:**
```
<div style="font-size:0.9rem" class="container mb-2 text-right">
  <svg class="icon" aria-hidden="true"><use xlink:href="#icon-lock"></use></svg>
  <a style="text-decoration:none" href="#">
    Connexion
  </a>
</div>
```

**Exemple de rendu visuel:**
![selection_243](https://user-images.githubusercontent.com/24526380/47915063-f49f9480-dea1-11e8-8adf-ac160225bc14.jpg)

Je vous laisse fine-tuner, créer une classe et faire le nécessaire.

**Comment by xentenza** [comment]
Ticket créé dans WebEvol https://epfl-webvolution.atlassian.net/browse/WEBEVOL-88
