### ISSUE TITLE
Icon: icon-filters ?

### ISSUE THREAD

**Issue by williambelle** [epfl-si/elements#352]
J'ai l'impression qu'il manque l'îcone ?

https://github.com/epfl-idevelop/elements/blob/2b8e42e9430610c579e12ef2b0b90dbc4e78a082/assets/components/molecules/filters/filters.twig#L13

Il n'apparaît pas en mode mobile sur https://epfl-idevelop.github.io/elements/#/pages/news-homepage

**Comment by knuch** [comment]
related to #289 
L'icone n'est pas encore dans le styleguide
