### ISSUE TITLE
Partial collapse : le bouton et le texte ne change pas une fois déplié

### ISSUE THREAD

**Issue by jdelasoie** [epfl-si/elements#365]
Cliquer sur le bouton "Show full biography" sur la page https://epfl-idevelop.github.io/elements/#/atoms/collapse dans la parte Partial collapse pour saisir le problème

**Comment by xentenza** [comment]
Incident ouvert dans WebEvol https://epfl-webvolution.atlassian.net/browse/WEBEVOL-60
