### ISSUE TITLE
Popover (atoms) - mauvais alignement si texte court

### ISSUE THREAD

**Issue by obieler** [epfl-si/elements#367]
Lorsqu'on clique sur le bouton, la bulle n'est pas bien alignée si le texte est court. 
Visiblement c'est lorsqu'on est sur une seule ligne.

https://epfl-idevelop.github.io/elements/#/atoms/popover

**Exemple:**
![selection_249](https://user-images.githubusercontent.com/24526380/49737327-e0af3580-fc8c-11e8-9312-0946f19d820a.jpg)

**Comment by xentenza** [comment]
Ticket créé sur WebEvol
https://epfl-webvolution.atlassian.net/browse/WEBEVOL-87
