### ISSUE TITLE
Comment mettre un élément dans un 'nav_aside' qui ne soit qu'un titre

### ISSUE THREAD

**Issue by jaepetto** [epfl-si/elements#386]
Salut,

j'essaye de mettre un `nav_aside` en place dont 1 des éléments ne devrait pas être un lien (titre de groupe):
```
<aside class="nav-aside-wrapper">
    <nav id="nav-aside" class="nav-aside" role="navigation" aria-describedby="nav-aside-title">
        <h2 class="h5 sr-only-xl">On the same topic</h2>
        <ul>
            <li class="active"><a href="/">About</a></li>
            <li>
                <a href="#">Teaching</a>
                <ul>
                    <li><a href="/credits">ECTS credits taught</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</aside>
```

J'aimerais que l'élément 'Teaching' ne soit pas un lien (il ne pointe sur aucun contenu en particulier), mais qu'il apparaisse correctement dans la navigation.

Quand je retire le tag `<a>`, la navigation n'apparait pas correctement:
![image](https://user-images.githubusercontent.com/2668031/57437596-633f1f80-7242-11e9-9058-3e2a89c4596b.png)

**Comment by lvenries** [comment]
Un lien dans le menu doit être clicable
