### ISSUE TITLE
View full render for Header in english fail

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-si/elements#413]
From the page https://epfl-idevelop.github.io/elements/#/organisms/header, clicking the "View full render" for [Header english](https://epfl-idevelop.github.io/elements/#/organisms/header/en/full) and [Header light english](https://epfl-idevelop.github.io/elements/#/organisms/header/light-en/full) fail.

**Comment by ponsfrilus** [comment]
Update: the new link is https://epfl-si.github.io/elements/#/organisms/header/full, and only the link to the default full header (french) is working (https://epfl-si.github.io/elements/#/organisms/header/full).

- ❌ Full German: https://epfl-si.github.io/elements/#/organisms/header/de/full
- ❌ Full English: https://epfl-si.github.io/elements/#/organisms/header/en/full
- ❌ Light default: https://epfl-si.github.io/elements/#/organisms/header/light/full

**Comment by domq** [comment]
#522 might have fixed this; waiting for release to close issue.

**Comment by ponsfrilus** [comment]
Seems fixed \œ/
