### ISSUE TITLE
Yellow background with thinner teaser?

### ISSUE THREAD

**Issue by williambelle** [epfl-si/elements#428]
I think it should be `$gray-100`.

From PR #425 :

https://github.com/epfl-si/elements/blob/bfd017135927b7e41a0dc5c1324aeb61eca0c3cc/assets/components/organisms/fullwidth-teaser/fullwidth-teaser.scss#L288

![yellow](https://user-images.githubusercontent.com/2843501/70652198-7db2fe80-1c52-11ea-8556-222c23bb09d3.png)

**Comment by jdelasoie** [comment]
Corrigé par #442 
Top, merci !
