### ISSUE TITLE
Problème de controle sur les vignettes de la gallerie après un "Force refresh"

### ISSUE THREAD

**Issue by jdelasoie** [epfl-si/elements#450]
Parfois, je fais un vrai rafraichissement (ctrl+shift+r) avec Firefox, les vignettes sous la gallerie ne sont plus utilisable sur https://epfl-si.github.io/elements/#/molecules/gallery.

Le problème n'a l'air de se présenter que sous github.io

**Comment by jdelasoie** [comment]
Le problème n'ait plus reproductible, je le ferme.

**Comment by mbi** [comment]
J'ai aussi ce problème, et je peux le reproduire 100% sur Chrome et Firefox, sur github.io mais également sur des sites "réels" basés sur Elements.  

Est-ce qu'on pourrait re-ouvrir et analyser cette issue, s.v.p?

**Comment by jdelasoie** [comment]
Bien vu pour le cache, en activant l'option "Disable cache" dans les devtools de Firefox, le problème redevient présent. 

Étonnament, impossible de reproduire le problème sur Chromium + Ubuntu, que ce soit avec cache ou sans cache..

**Comment by mbi** [comment]
Effectivement: j'arrive plus à reproduire sur Chrome sur github.io, mais à 100% sur Firefox avec un shift-refresh.

Sur un site utilisant Elements: sur Chrome, Firefox et Safari, je peux reproduire à 100% avec un shift-refresh. Dans ce cas les images sont sur un S3 externe au site, si ça peut aider.

**Comment by jdelasoie** [comment]
Retesté sur nos sites en production qui ont les images en local : aucun problème.

@mbi Je souhaiterais m'assurer que ce n'est pas une limitation propre à github.io, sur quel(s) site(s) constatez-vous le même problème ?

**Comment by jdelasoie** [comment]
Après [réécriture du JS](https://github.com/epfl-si/elements/pull/505), il me semble que le problème est résolu.

@mbi
Je prévois de merger bientôt, cependant, recevoir votre confirmation sur ce changement me serait une plus-value. Auriez-vous le temps de rejouer vos tests sur https://epfl-si.github.io/elements/#/molecules/gallery ?

**Comment by mbi** [comment]
@jdelasoie ça semble parfait merci!

Si ça peut aider pour tester je peux aussi volontiers déployer une nouvelle version de [vendors.min.js | vendors.bundle.js | app.bundle.js] sur enacvm0023.xaas.epfl.ch

**Comment by jdelasoie** [comment]
@mbi Volontiers ! Je viens donc de publier une nouvelle release, la 2.22.1

**Comment by mbi** [comment]
Déployé, tout bon! 👌
Encore merci.
