### ISSUE TITLE
Nav lang : <select> still usefull?

### ISSUE THREAD

**Issue by obieler** [epfl-si/elements#496]
https://epfl-si.github.io/elements/#/atoms/nav-lang

Is this `<select>` still usefull?

https://github.com/epfl-si/elements/blob/f116282f2f7d728d3aee98984ddea28feed5d935/assets/components/atoms/nav-lang/nav-lang.twig#L31-L45

Not anymore since v2.0.5?

**Comment by xentenza** [comment]
Oui: une partie du site sera traduite vers l'allemand, et certaines unités (notamment dans l'éducation) traduisent quelques pages également vers l'italien afin de toucher un public italophone.
