### ISSUE TITLE
[3h] Restauration - schedules

### ISSUE THREAD

**Issue by knuch** [epfl-si/elements#81]

**Comment by pierre-georges** [comment]
Design updated with mobile versions.
https://invis.io/9DMZV08HJ6Z#/295605678_Restauration_-_Menu

**Comment by zufrieden** [comment]
- [ ] Frontend Review needed

**Comment by zufrieden** [comment]
- [ ] Implémenter les schedules
- [x] Valider les schedules par @frizzymagma voir ci-dessous.
![screenshot 2018-09-20 15 26 34](https://user-images.githubusercontent.com/451236/45821488-a5364800-bce9-11e8-8381-713a66f4c79b.png)
